version: "3"

networks:
  genboard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:

  www:
    build:
      context: www
      dockerfile: Dockerfile-dev
    container_name: genboard-www-dev
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./www:/workspace
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - HOST=172.30.0.12
    networks:
      genboard:
        ipv4_address: 172.30.0.12

  api:
    build:
      context: api
      dockerfile: Dockerfile-dev
    container_name: genboard-api-dev
    entrypoint: 'tail -f /dev/null'
    volumes:
      - ./api:/workspace
      - ~/.m2/repository:/root/.m2/repository
    ports:
      - 8081:8080
    environment:
      - PORT=5000
      - HOST=172.30.0.21
    networks:
      genboard:
        ipv4_address: 172.30.0.21

  mysql:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: genboard-mysql-dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      genboard:
        ipv4_address: 172.30.0.31




#2018-04-07
