FROM node:6

RUN apt-get -q update \
  && apt-get install apt-utils --assume-yes \
  && apt-get install ruby-dev --assume-yes \
  && apt-get install rubygems --assume-yes \
  && gem update --system \
  && gem install compass \
  && rm -rf /var/lib/apt/lists/*

WORKDIR workspace
